#!/bin/bash
set -euo pipefail

# Submit one Slurm array task for each JSON option file generated by src/init.R.
# Usage:
#   ./tests/run_tests_slurm.sh <test_suite> <test_name>

usage() {
  cat <<'USAGE'
Usage:
  ./tests/run_tests_slurm.sh <test_suite> <test_name>

Environment options:
  Active profile is read from .env. Switch it with make build first.
  SLURM_RESOURCES     Resource class: default or heavy (default: default)
  SLURM_CPUS          Override cpus-per-task
  SLURM_MEM           Override memory
  SLURM_TIME          Override walltime
  SLURM_ARRAY_LIMIT   Limit concurrent array tasks, e.g. 20
  SLURM_COMPILE       Submit C++ compilation before test jobs (0/1)
  SLURM_COMPILE_MODEL Optional model to compile instead of --all
  SLURM_COMPILE_TARGET Optional target for SLURM_COMPILE_MODEL
  SLURM_COMPILE_CPUS  Compile job cpus-per-task
  SLURM_COMPILE_MEM   Compile job memory
  SLURM_COMPILE_TIME  Compile job walltime
  SLURM_AGGREGATE     Submit aggregate_results.R after all array tasks (0/1)
  SLURM_DRY_RUN       Print sbatch commands without submitting (0/1)
  SLURM_PARTITION     Optional Slurm partition
  SLURM_ACCOUNT       Optional Slurm account
  SLURM_QOS           Optional Slurm QoS
USAGE
}

is_truthy() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|y|Y) return 0 ;;
    *) return 1 ;;
  esac
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

TEST_SUITE="$1"
TEST_NAME="$2"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
RESOURCE_CLASS="${SLURM_RESOURCES:-default}"
DRY_RUN="${SLURM_DRY_RUN:-0}"
COMPILE_BEFORE_SUBMIT="${SLURM_COMPILE:-0}"
SUBMIT_AGGREGATE="${SLURM_AGGREGATE:-1}"

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export VECLIB_MAXIMUM_THREADS="${VECLIB_MAXIMUM_THREADS:-1}"

cd "${PROJECT_DIR}"
if [[ ! -f "${PROJECT_DIR}/.env" ]]; then
  echo "Error: .env not found. Run: make build TESTBENCH_PROFILE=<profile>"
  exit 1
fi

set -a
source "${PROJECT_DIR}/.env"
set +a

PROFILE="${TESTBENCH_PROFILE:-}"
if [[ -z "${PROFILE}" ]]; then
  echo "Error: TESTBENCH_PROFILE is not set in ${PROJECT_DIR}/.env"
  exit 1
fi

cd "${PATH_REPO}"

case "${RESOURCE_CLASS}" in
  default)
    CPUS="${SLURM_CPUS:-${DEFAULT_CPUS:-1}}"
    MEM="${SLURM_MEM:-${DEFAULT_MEM:-8GB}}"
    TIME="${SLURM_TIME:-${DEFAULT_TIME:-04:00:00}}"
    ;;
  heavy)
    CPUS="${SLURM_CPUS:-${HEAVY_CPUS:-${DEFAULT_CPUS:-1}}}"
    MEM="${SLURM_MEM:-${HEAVY_MEM:-${DEFAULT_MEM:-8GB}}}"
    TIME="${SLURM_TIME:-${HEAVY_TIME:-${DEFAULT_TIME:-04:00:00}}}"
    ;;
  *)
    echo "Error: SLURM_RESOURCES must be 'default' or 'heavy'." >&2
    exit 1
    ;;
esac

echo "Preparing queue for ${TEST_SUITE}/${TEST_NAME} using profile ${PROFILE}..."
Rscript src/init.R "${TEST_SUITE}" "${TEST_NAME}"

QUEUE_DIR="${PATH_QUEUE}/${TEST_SUITE}/${TEST_NAME}"
if [[ ! -d "${QUEUE_DIR}" ]]; then
  echo "Error: queue directory not found: ${QUEUE_DIR}" >&2
  exit 1
fi

OPTION_FILES=()
while IFS= read -r option_path; do
  OPTION_FILES+=("${option_path}")
done < <(find "${QUEUE_DIR}" -maxdepth 1 -type f -name '*.json' | sort)
if [[ "${#OPTION_FILES[@]}" -eq 0 ]]; then
  echo "Error: no JSON option files found in ${QUEUE_DIR}" >&2
  exit 1
fi

LOG_DIR="${PATH_LOGS}/slurm/${TEST_SUITE}/${TEST_NAME}"
mkdir -p "${LOG_DIR}"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
MANIFEST="${LOG_DIR}/options_${TIMESTAMP}.txt"
for option_path in "${OPTION_FILES[@]}"; do
  basename "${option_path}"
done > "${MANIFEST}"

N_OPTIONS="${#OPTION_FILES[@]}"
ARRAY_SPEC="1-${N_OPTIONS}"
if [[ -n "${SLURM_ARRAY_LIMIT:-}" ]]; then
  ARRAY_SPEC="${ARRAY_SPEC}%${SLURM_ARRAY_LIMIT}"
fi

JOB_SLUG="${TEST_SUITE}_${TEST_NAME}"
JOB_SLUG="${JOB_SLUG//[^A-Za-z0-9_]/_}"
JOB_SLUG="${JOB_SLUG:0:48}"
RUN_JOB_NAME="tb_${JOB_SLUG}"
AGG_JOB_NAME="tb_agg_${JOB_SLUG}"

SBATCH_COMMON=(
  --time="${TIME}"
  --mem="${MEM}"
  --cpus-per-task="${CPUS}"
)

if [[ -n "${SLURM_PARTITION:-}" ]]; then
  SBATCH_COMMON+=(--partition="${SLURM_PARTITION}")
fi
if [[ -n "${SLURM_ACCOUNT:-}" ]]; then
  SBATCH_COMMON+=(--account="${SLURM_ACCOUNT}")
fi
if [[ -n "${SLURM_QOS:-}" ]]; then
  SBATCH_COMMON+=(--qos="${SLURM_QOS}")
fi

RUN_WRAP=$(cat <<EOF
set -euo pipefail

cd '${PATH_REPO}'
set -a
source '${PROJECT_DIR}/.env'
set +a

export TESTBENCH_PROFILE='${PROFILE}'
export OMP_NUM_THREADS="\${OMP_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="\${OPENBLAS_NUM_THREADS:-1}"
export VECLIB_MAXIMUM_THREADS="\${VECLIB_MAXIMUM_THREADS:-1}"

option_file=\$(sed -n "\${SLURM_ARRAY_TASK_ID}p" '${MANIFEST}')
if [[ -z "\${option_file}" ]]; then
  echo "No option file found for SLURM_ARRAY_TASK_ID=\${SLURM_ARRAY_TASK_ID}" >&2
  exit 1
fi

echo '========================================'
echo 'Test suite: ${TEST_SUITE}'
echo 'Test name: ${TEST_NAME}'
echo "Option file: \${option_file}"
echo 'Started at:' \$(date)
echo 'Working directory:' \$(pwd)
echo "SLURM_JOB_ID: \${SLURM_JOB_ID:-unset}"
echo "SLURM_ARRAY_TASK_ID: \${SLURM_ARRAY_TASK_ID:-unset}"
echo "SLURM_CPUS_PER_TASK: \${SLURM_CPUS_PER_TASK:-unset}"
echo 'Thread limits:'
echo "  OMP_NUM_THREADS=\${OMP_NUM_THREADS}"
echo "  OPENBLAS_NUM_THREADS=\${OPENBLAS_NUM_THREADS}"
echo "  VECLIB_MAXIMUM_THREADS=\${VECLIB_MAXIMUM_THREADS}"
echo 'R library paths:'
Rscript -e 'print(.libPaths())'

Rscript 'tests/${TEST_SUITE}/main.R' '${TEST_NAME}' "\${option_file}"

echo 'Finished at:' \$(date)
echo '========================================'
EOF
)

AGG_WRAP=$(cat <<EOF
set -euo pipefail

cd '${PATH_REPO}'
set -a
source '${PROJECT_DIR}/.env'
set +a

export TESTBENCH_PROFILE='${PROFILE}'
export OMP_NUM_THREADS="\${OMP_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="\${OPENBLAS_NUM_THREADS:-1}"
export VECLIB_MAXIMUM_THREADS="\${VECLIB_MAXIMUM_THREADS:-1}"

echo '========================================'
echo 'Aggregating results for ${TEST_SUITE}/${TEST_NAME}'
echo 'Started at:' \$(date)
Rscript 'tests/${TEST_SUITE}/aggregate_results.R' '${TEST_NAME}'
echo 'Finished at:' \$(date)
echo '========================================'
EOF
)

run_sbatch() {
  if is_truthy "${DRY_RUN}"; then
    printf 'sbatch'
    printf ' %q' "$@"
    printf '\n'
    return 0
  fi

  sbatch "$@"
}

if ! is_truthy "${DRY_RUN}" && ! command -v sbatch >/dev/null 2>&1; then
  echo "Error: sbatch not found in PATH." >&2
  exit 1
fi

COMPILE_JOB_ID=""
if is_truthy "${COMPILE_BEFORE_SUBMIT}"; then
  COMPILE_ARGS=(--all)
  if [[ -n "${SLURM_COMPILE_MODEL:-}" ]]; then
    COMPILE_ARGS=("${SLURM_COMPILE_MODEL}")
    if [[ -n "${SLURM_COMPILE_TARGET:-}" ]]; then
      COMPILE_ARGS+=("${SLURM_COMPILE_TARGET}")
    fi
  fi

  echo "Submitting C++ compilation before test jobs..."
  if is_truthy "${DRY_RUN}"; then
    SLURM_DRY_RUN="${DRY_RUN}" \
    SLURM_COMPILE_CPUS="${SLURM_COMPILE_CPUS:-}" \
    SLURM_COMPILE_MEM="${SLURM_COMPILE_MEM:-}" \
    SLURM_COMPILE_TIME="${SLURM_COMPILE_TIME:-}" \
    SLURM_PARTITION="${SLURM_PARTITION:-}" \
    SLURM_ACCOUNT="${SLURM_ACCOUNT:-}" \
    SLURM_QOS="${SLURM_QOS:-}" \
      ./cpp/compile_slurm.sh "${COMPILE_ARGS[@]}"
    COMPILE_JOB_ID="<compile_job_id>"
  else
    COMPILE_JOB_ID=$(SLURM_DRY_RUN="${DRY_RUN}" \
      SLURM_COMPILE_CPUS="${SLURM_COMPILE_CPUS:-}" \
      SLURM_COMPILE_MEM="${SLURM_COMPILE_MEM:-}" \
      SLURM_COMPILE_TIME="${SLURM_COMPILE_TIME:-}" \
      SLURM_PARTITION="${SLURM_PARTITION:-}" \
      SLURM_ACCOUNT="${SLURM_ACCOUNT:-}" \
      SLURM_QOS="${SLURM_QOS:-}" \
        ./cpp/compile_slurm.sh --parsable "${COMPILE_ARGS[@]}")
    echo "Submitted compile job: ${COMPILE_JOB_ID}"
  fi
fi

RUN_DEPENDENCY_ARGS=()
if [[ -n "${COMPILE_JOB_ID}" ]]; then
  RUN_DEPENDENCY_ARGS=(--dependency="afterok:${COMPILE_JOB_ID}")
fi

echo "Submitting ${N_OPTIONS} option jobs (${RESOURCE_CLASS}: ${CPUS} CPUs, ${MEM}, ${TIME})..."
echo "Manifest: ${MANIFEST}"

if is_truthy "${DRY_RUN}"; then
  run_sbatch \
    --parsable \
    --job-name="${RUN_JOB_NAME}" \
    --array="${ARRAY_SPEC}" \
    --output="${LOG_DIR}/${RUN_JOB_NAME}_%A_%a.out" \
    --error="${LOG_DIR}/${RUN_JOB_NAME}_%A_%a.err" \
    "${RUN_DEPENDENCY_ARGS[@]}" \
    "${SBATCH_COMMON[@]}" \
    --wrap="${RUN_WRAP}"
else
  RUN_JOB_ID=$(run_sbatch \
    --parsable \
    --job-name="${RUN_JOB_NAME}" \
    --array="${ARRAY_SPEC}" \
    --output="${LOG_DIR}/${RUN_JOB_NAME}_%A_%a.out" \
    --error="${LOG_DIR}/${RUN_JOB_NAME}_%A_%a.err" \
    "${RUN_DEPENDENCY_ARGS[@]}" \
    "${SBATCH_COMMON[@]}" \
    --wrap="${RUN_WRAP}")

  echo "Submitted array job: ${RUN_JOB_ID}"
fi

if is_truthy "${SUBMIT_AGGREGATE}"; then
  AGG_CPUS="${SLURM_AGG_CPUS:-1}"
  AGG_MEM="${SLURM_AGG_MEM:-${DEFAULT_MEM:-8GB}}"
  AGG_TIME="${SLURM_AGG_TIME:-${DEFAULT_TIME:-04:00:00}}"

  if is_truthy "${DRY_RUN}"; then
    run_sbatch \
      --parsable \
      --job-name="${AGG_JOB_NAME}" \
      --output="${LOG_DIR}/${AGG_JOB_NAME}_%j.out" \
      --error="${LOG_DIR}/${AGG_JOB_NAME}_%j.err" \
      --time="${AGG_TIME}" \
      --mem="${AGG_MEM}" \
      --cpus-per-task="${AGG_CPUS}" \
      --dependency="afterok:<array_job_id>" \
      --wrap="${AGG_WRAP}"
  else
    AGG_JOB_ID=$(run_sbatch \
      --parsable \
      --job-name="${AGG_JOB_NAME}" \
      --output="${LOG_DIR}/${AGG_JOB_NAME}_%j.out" \
      --error="${LOG_DIR}/${AGG_JOB_NAME}_%j.err" \
      --time="${AGG_TIME}" \
      --mem="${AGG_MEM}" \
      --cpus-per-task="${AGG_CPUS}" \
      --dependency="afterok:${RUN_JOB_ID}" \
      --wrap="${AGG_WRAP}")

    echo "Submitted aggregate job: ${AGG_JOB_ID}"
  fi
fi
